# Generated by Django 4.1 on 2024-03-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='genre',
            field=models.CharField(blank=True, choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('sci-fi', 'Science Fiction'), ('horror', 'Horror'), ('self-help', 'Self-Help')], default='action', max_length=10),
        ),
    ]
