# Generated by Django 4.1 on 2024-04-10 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
