# Generated by Django 4.1 on 2024-04-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_uploadedfile_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
    ]
