# Generated by Django 4.1 on 2024-04-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShelfSpaceBlogs', '0002_blogpost_upvoted_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='upvoted_users',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='upvoted_users',
            field=models.IntegerField(default=0),
        ),
    ]
