# Generated by Django 4.1 on 2024-04-15 04:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ShelfSpaceBlogs', '0003_remove_blogpost_upvoted_users_blogpost_upvoted_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='upvoted_users',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='upvoted_users',
            field=models.ManyToManyField(blank=True, related_name='upvoted_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
